import { Goal } from '../types';

export const EXAMPLE_GOALS: Omit<Goal, 'id' | 'createdAt'>[] = [
  {
    title: 'Get Married Before 40',
    description: 'I am building a loving, committed relationship and creating a beautiful family.',
    targetAge: 40,
    category: 'relationships',
    emoji: '💍',
    position: { x: 100, y: 150 },
    size: { width: 320, height: 400 },
    achieved: false,
  },
  {
    title: 'Own a Luxury Car',
    description: 'I am successful and abundant. I drive my dream car with pride and gratitude.',
    targetYear: 2027,
    category: 'finances',
    emoji: '🏎️',
    position: { x: 450, y: 150 },
    size: { width: 320, height: 400 },
    achieved: false,
  },
  {
    title: 'Travel the World',
    description: 'I explore new cultures, experience breathtaking places, and create unforgettable memories.',
    targetAge: 35,
    category: 'adventure',
    emoji: '✈️',
    position: { x: 800, y: 150 },
    size: { width: 320, height: 400 },
    achieved: false,
  },
  {
    title: 'Build a 7-Figure Business',
    description: 'I am a successful entrepreneur creating value and abundance for myself and others.',
    targetYear: 2028,
    category: 'career',
    emoji: '💼',
    position: { x: 100, y: 580 },
    size: { width: 320, height: 400 },
    achieved: false,
  },
  {
    title: 'Get Fit & Strong',
    description: 'I am healthy, energetic, and strong. I take care of my body and feel amazing every day.',
    category: 'health',
    emoji: '💪',
    position: { x: 450, y: 580 },
    size: { width: 320, height: 400 },
    achieved: false,
  },
  {
    title: 'Master a New Skill',
    description: 'I am constantly learning and growing. I invest in myself and my personal development.',
    targetAge: 32,
    category: 'growth',
    emoji: '🎯',
    position: { x: 800, y: 580 },
    size: { width: 320, height: 400 },
    achieved: false,
  },
];
